config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#index'

  resources :users, only: :show do
  resources :listings, only: [:index, :show, :create, :edit, :update, :new]
end

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  

 

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  def self.create_with_omniauth(auth_hash)
     auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end
  
  def update_token(auth_hash)
     self.token = auth_hash["credentials"]["token"]
     self.save
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
   



      belongs_to :user
 
   
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

has_many :authentications, :dependent => :destroy
has_many :listings

def self.create_with_auth_and_hash(authentication, auth_hash)
   # user = User.create(first_name: auth_hash["first_name"], email: auth_hash["extra"]["raw_info"]["email"])
   user = User.create!(first_name: auth_hash["extra"]["raw_info"]["first_name"], last_name: auth_hash["extra"]["raw_info"]["last_name"], email: auth_hash["extra"]["raw_info"]["email"])

   user.authentications<<(authentication)
   
   return user 
end

def fb_token
   x = self.authentications.where(:provider => :facebook).first
   return x.token unless x.nil?
end

def password_optional?
   true
end
   
   
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

   def show 
      @listing = Listing.find(params[:id])
   end
   
   def index
      @listing = Listing.all
   end
   
   def new
      @listing = current_user.listings.new
   end

   def create
      @listing = current_user.listings.new(listing_params)
      @listing.user_id = current_user.id
      
   if @listing.save
      
      redirect_to listing_path(current_user)
   end
   end
   
   def find_listing
      @listing = Listing.find(params[:id])
   end
      
   def edit
   end
        
   def update
      if @listing.update(listing_params)
         flash[:success] = "Successfully updated the listing"
         redirect_to @listing
      else
         flash[:danger] = "Error updating list"
         render :edit
      end
   end

private
   def listing_params
   params.require(:listing).permit(:title, :address, :bedroom, :bathroom, :max_guest, :description, :internet, :pet, :smoker, :price, :user_id )
   end
   
   
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   
   def create_from_omniauth
      auth_hash = request.env["omniauth.auth"]
      authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
      
      if authentication.user
         user = authentication.user
         authentication.update_token(auth_hash)
         @next = root_url
         @notice = "Signed in!"
      else
         user = User.create_with_auth_and_hash(authentication, auth_hash)
         # @next = edit_user_path(user)
         @notice = "User created - confirm or edit details"
      end
      
      sign_in(user)
      
      redirect_to root_path, :notice => @notice
   end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
     before_action :require_login, only: [:users]

    
     def home
          @user = User.new
     end
     
end

app/controllers/suspeneded_check_guards_controller.rb
class SuspenededCheckGuardsController < ApplicationController
 def call
    if suspended?
      failure("Your account is suspended.")
    else
      next_guard
    end
  end

  def suspended?
    current_user.suspended?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   before_action :require_login, only: [:show]
   
   def show
   end

   def new
      @user = User.new
   end
  
  
   def create
      @user = User.new(user_params)
      
      if @user.save
         redirect_to users_path
      else
         
         render 'new'
      end
   end
     
   def edit
   end
   
   def update
      if @user.update(user_params)
         flash[:success] = "Successfully updated the user"
         redirect_to @user
      else
         flash[:danger] = "Error updating user"
         render :edit
      end
   end
   
   def find_user
    @user = User.find(params[:id])
   end


   private
   def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
   end
    
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suspeneded_check_guards_helper.rb
module SuspenededCheckGuardsHelper
end

app/helpers/users_helper.rb
module UsersHelper


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, intial-scale=1.0">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  
   <!--Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

 <!--Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

 <!--Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>




</head>
<body>
  
<!--Navbar-->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      
<ul class="nav navbar-nav">
  
    <li><%= link_to 'PairBnb', root_path, class: 'navbar-brand' %></li>
      
<% if signed_in? -%>

    <li><%= link_to "UserProfile", user_path(current_user), class: "navbar-brand" %></li>
    <li><%= link_to "Listings", user_listings_path(current_user), class: "navbar-brand" %></li>

<% else -%>

    <li><%= link_to t(".sign_in"), sign_in_path %></li>

<% end -%>
</ul>

    </div>
  </div>
</nav>
<!--Navbar-->
  
  <div id="header">
   <% if signed_in? -%>
         Signed in as: <%= current_user.email %>
       <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
   <% end -%>
 </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render "listings/form" %>

app/views/listings/form.html.erb
<h3>Hello <%= current_user.first_name %>. List a property here!</h3><br>


<%= form_for @listing do |l| %>
           
         <div class="form-control">
            <%= l.label :title %>
            <%= l.text_field :title %>
         </div>  
         <div class="form-control">
            <%= l.label :address %>
            <%= l.text_field :address %>
         </div>  
         <div class="form-control">
            <%= l.label :bedroom %>
            <%= l.text_field :bedroom %>
         </div> 
         <div class="form-control">
            <%= l.label :bathroom %>
            <%= l.text_field :bathroom %>
         </div> 
         <div class="form-control">
            <%= l.label :max_guest %>
            <%= l.text_field :max_guest %>
         </div>  
          <div class="form-control">
            <%= l.label :description %>
            <%= l.text_field :description %>
         </div> 
          <div class="form-control">
            <%= l.label :internet %>
            <%= l.text_field :internet %>
         </div> 
          <div class="form-control">
            <%= l.label :pet %>
            <%= l.text_field :pet %>
         </div> 
          <div class="form-control">
            <%= l.label :smoker %>
            <%= l.text_field :smoker %>
         </div> 
          <div class="form-control">
            <%= l.label :price %>
            <%= l.text_field :price %>
         </div> 
         
         <%= l.submit %>
         
         <% end -%>

app/views/listings/index.html.erb
<h3>Hello <%= current_user.first_name %>. Create a Listing below!</h3><br>

First Name: <%= current_user.first_name %> <br>
Last Name:  <%= current_user.last_name %>  <br>
Email:      <%= current_user.email %>      <br>

<br>
<br>
<br>

<%= link_to "Create New Listing", new_user_listing_url %><br>
<br>

app/views/listings/new.html.erb
<% if signed_in? -%>


<h3>Hello <%= current_user.first_name %>. List a property here!</h3><br>

First Name: <%= current_user.first_name %> <br>
Last Name:  <%= current_user.last_name %>  <br>
Email:      <%= current_user.email %>      <br>
           

<%= form_for [current_user, @listing] do |e| %>
           
         <div class="form-control">
            <%= e.label :title %>
            <%= e.text_field :title %>
         </div>  
         <div class="form-control">
            <%= e.label :address %>
            <%= e.text_field :address %>
         </div>  
         <div class="form-control">
            <%= e.label :bedroom %>
            <%= e.text_field :bedroom %>
         </div> 
         <div class="form-control">
            <%= e.label :bathroom %>
            <%= e.text_field :bathroom %>
         </div> 
         <div class="form-control">
            <%= e.label :max_guest %>
            <%= e.text_field :max_guest %>
         </div>  
          <div class="form-control">
            <%= e.label :description %>
            <%= e.text_field :description %>
         </div> 
          <div class="form-control">
            <%= e.label :internet %>
            <%= e.text_field :internet %>
         </div> 
          <div class="form-control">
            <%= e.label :pet %>
            <%= e.text_field :pet %>
         </div> 
          <div class="form-control">
            <%= e.label :smoker %>
            <%= e.text_field :smoker %>
         </div> 
          <div class="form-control">
            <%= e.label :price %>
            <%= e.text_field :price %>
         </div> 
         
         <%= e.submit %>
         
         <% end -%>
     
         
<% else -%>
<%= link_to t(".sign_in"), sign_in_path %>
<% end -%>

app/views/listings/show.html.erb
<h4>Hi! Welcome to your Listings Page</h4>
<br>
<br>
<br>
<% if signed_in? -%>

First Name: <%= current_user.first_name %> <br>
Last Name:  <%= current_user.last_name %>  <br>
Email:      <%= current_user.email %>
<br>
<br>
<br>

<%form_for @listing do |e| %>

<h1>Title: <%= e.title %></h1>
<p>Address: <%= e.address %><p>
<p>Bedroom: <%= e.bedroom %><p>
<p>Bathroom: <%= e.bathroom %><p>
<p>Max_guest: <%= e.max_guest %><p>
<p>Description: <%= e.description %><p>
<p>Internet: <%= e.internet %><p>
<p>Pet: <%= e.pet %><p>
<p>Smoker: <%= e.smoker %><p>
<p>Price: <%= e.price %><p>

<%= link_to "Edit", edit_listening_path(@listing) %>


<div class="digg_pagination">
<div class="page_info">
    <%= page_entries_info @posts %>
</div>
    <%= will_paginate @posts, :container => false %>
</div>
  
<% end %>
<% end %>

app/views/static_pages/index.html.erb
<h1> HARO HARO THIS IS HOME PAGE</h1>

<%= link_to "Sign in with Facebook", "/auth/facebook" %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<!-- , id: "edit_link", remote: true -->

<h3>Hello <%= current_user.first_name %> This is your Profile Page</h3>


First Name: <%= current_user.first_name %> <br>
Last Name:  <%= current_user.last_name %>  <br>
Email:      <%= current_user.email %>
           
      
           

           
           
           
           
           
           